#!/usr/bin/env php
<?php

if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

$rootDir = getcwd();

$application = new \Shopware\Psh\Application\Application($rootDir);
$result = $application->run($argv);
exit($result);
