#!/usr/bin/env php
<?php

if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}
$application = new \Shopware\Psh\Application\Application(__DIR__);
$application->run($argv);